name = "website"
compatibility_date = "2024-09-23"

# Cloudflare Pages static site deployment
# Build command : npm run build
# Output directory: dist/drebel-website/browser

[assets]
directory = "./dist/drebel-website/browser"